name: Send Sync Request On Release

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Send Sync Request
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.EDITOR_REPOSITORY_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/opengql/editor/actions/workflows/synchronize-with-grammar-repo.yml/dispatches \
            -d '{"ref":"main"}'

      - name: Send Sync Request
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.EDITOR_REPOSITORY_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/opengql/railroad/actions/workflows/deploy-application.yml/dispatches \
            -d '{"ref":"main"}'